[tmdb]
api_key = ""
base_url = "https://api.themoviedb.org/3"
# 可选：["zh-CN", "zh-TW", "zh-HK"]
languages = ["zh-CN"]

[output]
dir = "~/.local/share/fcitx5/rime"
lock_path = "~/.local/state/rime-pinyin-tmdb-generator/update.lock"

[bootstrap]
request_interval = "50ms"
min_popularity = 10
movie_min_popularity = 15

[rime]
redeploy_command = ""
